### ISSUE TITLE
Cari Conversation Starters

### ISSUE THREAD

**Issue by corneliusyan** [fluent-git/fluent-fe#10]
1. *Free Talk*
2. Culture
3. Food
4. Game
5. Health
6. Job
7. Movie
8. Place
9. Politic
10. Technology
11. Trend
12. Sport

**Comment by HansaHalim** [comment]
https://docs.google.com/document/d/1vNyv0qskukMvpLFEEKfxhT2qFPZynaTkqqfPgckByVg/edit?usp=sharing

**Comment by HansaHalim** [comment]
Done
